window.LANG_MAP = {
	afrikaans: "af", af: "af",
	albanian: "sq", sq: "sq",
	amharic: "am", am: "am",
	arabic: "ar", ar: "ar",
	armenian: "hy", hy: "hy",
	assamese: "as", as: "as",
	aymara: "ay", ay: "ay",
	azerbaijani: "az", az: "az",
	bambara: "bm", bm: "bm",
	basque: "eu", eu: "eu",
	belarusian: "be", be: "be",
	bengali: "bn", bn: "bn",
	bhojpuri: "bho", bho: "bho",
	bosnian: "bs", bs: "bs",
	bulgarian: "bg", bg: "bg",
	catalan: "ca", ca: "ca",
	cebuano: "ceb", ceb: "ceb",
	"chinese (simplified)": "zh-CN", "chinese simplified": "zh-CN", "zh-cn": "zh-CN",
	"chinese (traditional)": "zh-TW", "chinese traditional": "zh-TW", "zh-tw": "zh-TW",
	chinese: "zh-CN", zh: "zh-CN",
	corsican: "co", co: "co",
	croatian: "hr", hr: "hr",
	czech: "cs", cs: "cs",
	danish: "da", da: "da",
	dhivehi: "dv", dv: "dv",
	dogri: "doi", doi: "doi",
	dutch: "nl", nl: "nl",
	english: "en", en: "en",
	esperanto: "eo", eo: "eo",
	estonian: "et", et: "et",
	ewe: "ee", ee: "ee",
	filipino: "fil", fil: "fil",
	tagalog: "tl", tl: "tl",
	finnish: "fi", fi: "fi",
	french: "fr", fr: "fr",
	frisian: "fy", fy: "fy",
	galician: "gl", gl: "gl",
	georgian: "ka", ka: "ka",
	german: "de", de: "de",
	greek: "el", el: "el",
	guarani: "gn", gn: "gn",
	gujarati: "gu", gu: "gu",
	"haitian creole": "ht", haitian: "ht", ht: "ht",
	hausa: "ha", ha: "ha",
	hawaiian: "haw", haw: "haw",
	hebrew: "he", iw: "he", he: "he",
	hindi: "hi", hi: "hi",
	hmong: "hmn", hmn: "hmn",
	hungarian: "hu", hu: "hu",
	icelandic: "is", is: "is",
	igbo: "ig", ig: "ig",
	ilocano: "ilo", ilo: "ilo",
	indonesian: "id", id: "id",
	irish: "ga", ga: "ga",
	italian: "it", it: "it",
	japanese: "ja", ja: "ja",
	javanese: "jv", jw: "jv", jv: "jv",
	kannada: "kn", kn: "kn",
	kazakh: "kk", kk: "kk",
	khmer: "km", km: "km",
	kinyarwanda: "rw", rw: "rw",
	konkani: "gom", gom: "gom",
	korean: "ko", ko: "ko",
	krio: "kri", kri: "kri",
	"kurdish (kurmanji)": "ku", kurmanji: "ku", ku: "ku",
	"kurdish (sorani)": "ckb", sorani: "ckb", ckb: "ckb",
	kyrgyz: "ky", ky: "ky",
	lao: "lo", lo: "lo",
	latin: "la", la: "la",
	latvian: "lv", lv: "lv",
	lingala: "ln", ln: "ln",
	lithuanian: "lt", lt: "lt",
	luganda: "lg", lg: "lg",
	luxembourgish: "lb", lb: "lb",
	macedonian: "mk", mk: "mk",
	maithili: "mai", mai: "mai",
	malagasy: "mg", mg: "mg",
	malay: "ms", ms: "ms",
	malayalam: "ml", ml: "ml",
	maltese: "mt", mt: "mt",
	maori: "mi", mi: "mi",
	marathi: "mr", mr: "mr",
	"meitei (manipuri)": "mni-Mtei", manipuri: "mni-Mtei", meitei: "mni-Mtei", "mni-mtei": "mni-Mtei",
	mizo: "lus", lus: "lus",
	mongolian: "mn", mn: "mn",
	myanmar: "my", burmese: "my", my: "my",
	nepali: "ne", ne: "ne",
	norwegian: "no", no: "no",
	"nyanja (chichewa)": "ny", nyanja: "ny", chichewa: "ny", ny: "ny",
	odia: "or", oriya: "or", or: "or",
	oromo: "om", om: "om",
	pashto: "ps", ps: "ps",
	persian: "fa", farsi: "fa", fa: "fa",
	polish: "pl", pl: "pl",
	portuguese: "pt", pt: "pt",
	punjabi: "pa", pa: "pa",
	quechua: "qu", qu: "qu",
	romanian: "ro", ro: "ro",
	russian: "ru", ru: "ru",
	samoan: "sm", sm: "sm",
	sanskrit: "sa", sa: "sa",
	"scots gaelic": "gd", scottish: "gd", gd: "gd",
	sepedi: "nso", nso: "nso",
	serbian: "sr", sr: "sr",
	sesotho: "st", st: "st",
	shona: "sn", sn: "sn",
	sindhi: "sd", sd: "sd",
	sinhala: "si", sinhalese: "si", si: "si",
	slovak: "sk", sk: "sk",
	slovenian: "sl", sl: "sl",
	somali: "so", so: "so",
	spanish: "es", es: "es",
	sundanese: "su", su: "su",
	swahili: "sw", sw: "sw",
	swati: "ss", ss: "ss",
	swedish: "sv", sv: "sv",
	tajik: "tg", tg: "tg",
	tamil: "ta", ta: "ta",
	tatar: "tt", tt: "tt",
	telugu: "te", te: "te",
	thai: "th", th: "th",
	tigrinya: "ti", ti: "ti",
	tsonga: "ts", ts: "ts",
	turkish: "tr", tr: "tr",
	turkmen: "tk", tk: "tk",
	twi: "ak", ak: "ak",
	ukrainian: "uk", uk: "uk",
	urdu: "ur", ur: "ur",
	uyghur: "ug", ug: "ug",
	uzbek: "uz", uz: "uz",
	vietnamese: "vi", vi: "vi",
	welsh: "cy", cy: "cy",
	xhosa: "xh", xh: "xh",
	yiddish: "yi", yi: "yi",
	yoruba: "yo", yo: "yo",
	zulu: "zu", zu: "zu",
};